# Generated by Django 2.2.6 on 2021-01-09 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_follow_is_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='is_following',
        ),
    ]
